wandb_version: 1

batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 150
hidden_dim:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.001
num_gin_layers:
  desc: null
  value: 3
num_lin_layers:
  desc: null
  value: 1
random_seed:
  desc: null
  value: 42
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705236927.36443
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.10.13
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
